version: 2.1

jobs:
  build:

    macos:
      xcode: 11.0.0

    steps:
      - checkout
      - run: pod install # Install CocoaPods dependencies
      - run: fastlane scan # Run tests using Fastlane

      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output
